# Generated by Django 4.0.1 on 2022-02-22 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='чертеж')),
                ('order_number', models.IntegerField(verbose_name='номер заказа')),
                ('contract', models.TextField(verbose_name='номер договора')),
                ('qr', models.ImageField(default=None, upload_to='', verbose_name='QR-код')),
                ('start_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('weight', models.FloatField(verbose_name='масса')),
                ('unit', models.IntegerField(verbose_name='количество')),
                ('start_data1', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start1', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('fill1', models.BooleanField(verbose_name='заполнение')),
                ('history1', models.TextField(default='', verbose_name='история')),
                ('otk1', models.TextField(default='', verbose_name='ОТК')),
                ('sent1', models.BooleanField(default=False, verbose_name='отправлено')),
                ('end1', models.TextField(default='', verbose_name='закончен')),
                ('end1_otk', models.BooleanField(default=False, verbose_name='ОТК закончен')),
                ('start_data2', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start2', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('fill2', models.BooleanField(verbose_name='заполнение')),
                ('history2', models.TextField(default='', verbose_name='история')),
                ('otk2', models.TextField(default='', verbose_name='ОТК')),
                ('sent2', models.BooleanField(default=False, verbose_name='отправлено')),
                ('end2', models.TextField(default='', verbose_name='закончен')),
                ('end2_otk', models.BooleanField(default=False, verbose_name='ОТК закончен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Detal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='чертеж')),
                ('order_number', models.IntegerField(verbose_name='номер чертежа')),
                ('qr', models.ImageField(default=None, upload_to='', verbose_name='QR-код')),
                ('start_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('weight', models.FloatField(verbose_name='масса')),
                ('unit', models.IntegerField(verbose_name='количество')),
                ('start_data3', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start3', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('fill3', models.BooleanField(verbose_name='заполнение')),
                ('history3', models.TextField(default='', verbose_name='история')),
                ('otk3', models.TextField(default='', verbose_name='ОТК')),
                ('sent3', models.BooleanField(default=False, verbose_name='отправлено')),
                ('end3', models.TextField(default='', verbose_name='закончен')),
                ('end3_otk', models.BooleanField(default=False, verbose_name='ОТК закончен')),
                ('start_data4', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start4', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('fill4', models.BooleanField(verbose_name='заполнение')),
                ('history4', models.TextField(default='', verbose_name='история')),
                ('otk4', models.TextField(default='', verbose_name='ОТК')),
                ('sent4', models.BooleanField(default=False, verbose_name='отправлено')),
                ('end4', models.TextField(default='', verbose_name='закончен')),
                ('end4_otk', models.BooleanField(default=False, verbose_name='ОТК закончен')),
                ('start_data5', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start5', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('fill5', models.BooleanField(verbose_name='заполнение')),
                ('history5', models.TextField(default='', verbose_name='история')),
                ('otk5', models.TextField(default='', verbose_name='ОТК')),
                ('sent5', models.BooleanField(default=False, verbose_name='отправлено')),
                ('end5', models.TextField(default='', verbose_name='закончен')),
                ('end5_otk', models.BooleanField(default=False, verbose_name='ОТК закончен')),
                ('start_data6', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start6', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('fill6', models.BooleanField(verbose_name='заполнение')),
                ('history6', models.TextField(default='', verbose_name='история')),
                ('otk6', models.TextField(default='', verbose_name='ОТК')),
                ('sent6', models.BooleanField(default=False, verbose_name='отправлено')),
                ('end6', models.TextField(default='', verbose_name='закончен')),
                ('end6_otk', models.BooleanField(default=False, verbose_name='ОТК закончен')),
                ('start_data7', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start7', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('fill7', models.BooleanField(verbose_name='заполнение')),
                ('history7', models.TextField(default='', verbose_name='история')),
                ('otk7', models.TextField(default='', verbose_name='ОТК')),
                ('sent7', models.BooleanField(default=False, verbose_name='отправлено')),
                ('end7', models.TextField(default='', verbose_name='закончен')),
                ('end7_otk', models.BooleanField(default=False, verbose_name='ОТК закончен')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.factory', verbose_name='детали')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.CreateModel(
            name='ContractUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.IntegerField(verbose_name='номер договора')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.factory', verbose_name='factory, которому принадлежит контракт')),
            ],
        ),
    ]
