# Generated by Django 3.2.8 on 2021-12-29 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211227_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='factory',
            name='end_start1',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AddField(
            model_name='factory',
            name='end_start2',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AddField(
            model_name='factory',
            name='end_start3',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AddField(
            model_name='factory',
            name='end_start4',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AddField(
            model_name='factory',
            name='end_start5',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AddField(
            model_name='factory',
            name='end_start6',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AddField(
            model_name='factory',
            name='start_data1',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AddField(
            model_name='factory',
            name='start_data2',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AddField(
            model_name='factory',
            name='start_data3',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AddField(
            model_name='factory',
            name='start_data4',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AddField(
            model_name='factory',
            name='start_data5',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AddField(
            model_name='factory',
            name='start_data6',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='end_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='start_data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
    ]
