# Generated by Django 3.2.8 on 2022-01-03 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211229_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='end_start7',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AddField(
            model_name='factory',
            name='start_data7',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
    ]
