# Generated by Django 3.2.8 on 2022-01-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_detal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detal',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='detal',
            name='order_number',
        ),
    ]
