# Generated by Django 3.2.8 on 2022-01-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220108_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detal',
            name='weight_total',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='weight_total',
        ),
    ]
