# Generated by Django 3.2.8 on 2022-01-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220110_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detal',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='detal',
            name='order_number',
        ),
    ]
