# Generated by Django 3.2.8 on 2022-01-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_detal_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='qr',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
