# Generated by Django 3.2.9 on 2022-01-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_factory_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='detal',
            name='qr',
            field=models.ImageField(default=0, upload_to='', verbose_name='QR-код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factory',
            name='qr',
            field=models.ImageField(upload_to='', verbose_name='QR-код'),
        ),
    ]
