# Generated by Django 3.2.9 on 2022-01-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220118_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detal',
            name='order_number',
            field=models.IntegerField(verbose_name='номер чертежа'),
        ),
    ]
