# Generated by Django 3.2.8 on 2022-01-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220122_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='sent1',
            field=models.BooleanField(default=False, verbose_name='отправлено'),
        ),
        migrations.AddField(
            model_name='factory',
            name='sent2',
            field=models.BooleanField(default=False, verbose_name='отправлено'),
        ),
        migrations.AddField(
            model_name='factory',
            name='sent3',
            field=models.BooleanField(default=False, verbose_name='отправлено'),
        ),
        migrations.AddField(
            model_name='factory',
            name='sent4',
            field=models.BooleanField(default=False, verbose_name='отправлено'),
        ),
        migrations.AddField(
            model_name='factory',
            name='sent5',
            field=models.BooleanField(default=False, verbose_name='отправлено'),
        ),
        migrations.AddField(
            model_name='factory',
            name='sent6',
            field=models.BooleanField(default=False, verbose_name='отправлено'),
        ),
        migrations.AddField(
            model_name='factory',
            name='sent7',
            field=models.BooleanField(default=False, verbose_name='отправлено'),
        ),
    ]
