# Generated by Django 4.0.1 on 2022-02-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_star6_factory_start6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detal',
            name='qr',
            field=models.ImageField(default=None, upload_to='', verbose_name='QR-код'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='qr',
            field=models.ImageField(default=None, upload_to='', verbose_name='QR-код'),
        ),
    ]
