# Generated by Django 4.0.1 on 2022-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_detal_qr_alter_factory_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='start1',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start2',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start3',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start4',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start5',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start6',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start7',
        ),
        migrations.AddField(
            model_name='factory',
            name='history1',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='factory',
            name='history2',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='factory',
            name='history3',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='factory',
            name='history4',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='factory',
            name='history5',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='factory',
            name='history6',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='factory',
            name='history7',
            field=models.TextField(default='', verbose_name='история'),
        ),
    ]
