# Generated by Django 4.0.1 on 2022-02-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_factory_start1_remove_factory_start2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='otk1',
            field=models.DateTimeField(default=None, verbose_name='ОТК'),
        ),
        migrations.AddField(
            model_name='factory',
            name='otk2',
            field=models.DateTimeField(default=None, verbose_name='ОТК'),
        ),
        migrations.AddField(
            model_name='factory',
            name='otk3',
            field=models.DateTimeField(default=None, verbose_name='ОТК'),
        ),
        migrations.AddField(
            model_name='factory',
            name='otk4',
            field=models.DateTimeField(default=None, verbose_name='ОТК'),
        ),
        migrations.AddField(
            model_name='factory',
            name='otk5',
            field=models.DateTimeField(default=None, verbose_name='ОТК'),
        ),
        migrations.AddField(
            model_name='factory',
            name='otk6',
            field=models.DateTimeField(default=None, verbose_name='ОТК'),
        ),
        migrations.AddField(
            model_name='factory',
            name='otk7',
            field=models.DateTimeField(default=None, verbose_name='ОТК'),
        ),
    ]
