# Generated by Django 4.0.1 on 2022-02-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_detal_sent3_detal_sent4_detal_sent5_detal_sent6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detal',
            name='end3',
            field=models.TextField(default='', verbose_name='закончен'),
        ),
        migrations.AddField(
            model_name='detal',
            name='end4',
            field=models.TextField(default='', verbose_name='закончен'),
        ),
        migrations.AddField(
            model_name='detal',
            name='end5',
            field=models.TextField(default='', verbose_name='закончен'),
        ),
        migrations.AddField(
            model_name='detal',
            name='end6',
            field=models.TextField(default='', verbose_name='закончен'),
        ),
        migrations.AddField(
            model_name='detal',
            name='end7',
            field=models.TextField(default='', verbose_name='закончен'),
        ),
        migrations.AddField(
            model_name='factory',
            name='end1',
            field=models.TextField(default='', verbose_name='закончен'),
        ),
        migrations.AddField(
            model_name='factory',
            name='end2',
            field=models.TextField(default='', verbose_name='закончен'),
        ),
    ]
