# Generated by Django 3.2.8 on 2022-01-03 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220103_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='чертеж')),
                ('order_number', models.IntegerField(verbose_name='номер заказа')),
                ('contract', models.IntegerField(verbose_name='номер договора')),
                ('start_data', models.DateField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start', models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('weight', models.FloatField(verbose_name='масса')),
                ('start_data1', models.DateField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start1', models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('start_data2', models.DateField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start2', models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('start_data3', models.DateField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start3', models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('start_data4', models.DateField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start4', models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('start_data5', models.DateField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start5', models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('start_data6', models.DateField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start6', models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('start_data7', models.DateField(default=django.utils.timezone.now, verbose_name='дата начало')),
                ('end_start7', models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.factory', verbose_name='детали')),
            ],
        ),
    ]
