# Generated by Django 3.2.8 on 2022-01-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220103_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detal',
            options={'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
        migrations.AddField(
            model_name='detal',
            name='contract',
            field=models.TextField(default=0, verbose_name='номер договора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detal',
            name='order_number',
            field=models.IntegerField(default=0, verbose_name='номер заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detal',
            name='unit',
            field=models.IntegerField(default=0, verbose_name='количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detal',
            name='weight_total',
            field=models.FloatField(default=0, verbose_name='общая масса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='unit',
            field=models.IntegerField(default=0, verbose_name='количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='weight_total',
            field=models.FloatField(default=0, verbose_name='общая масса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factory',
            name='contract',
            field=models.TextField(verbose_name='номер договора'),
        ),
    ]
