# Generated by Django 3.2.8 on 2022-01-10 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220110_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detal',
            name='end_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='end_start1',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='end_start2',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='end_start3',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='end_start4',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='end_start5',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='end_start6',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='end_start7',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='start_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='start_data1',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='start_data2',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='start_data3',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='start_data4',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='start_data5',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='start_data6',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AlterField(
            model_name='detal',
            name='start_data7',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
    ]
