# Generated by Django 3.2.8 on 2022-01-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220115_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detal',
            name='contract',
        ),
    ]
