# Generated by Django 3.2.9 on 2022-01-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_detal_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='fill1',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='fill2',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='fill3',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='fill4',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='fill5',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='fill6',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='fill7',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
    ]
