# Generated by Django 3.2.8 on 2022-01-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220118_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='detal',
            name='fill1',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detal',
            name='fill2',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detal',
            name='fill3',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detal',
            name='fill4',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detal',
            name='fill5',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detal',
            name='fill6',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detal',
            name='fill7',
            field=models.BooleanField(default=0, verbose_name='заполнение'),
            preserve_default=False,
        ),
    ]
