# Generated by Django 3.2.8 on 2022-01-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220124_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='signal',
            field=models.BooleanField(default=False),
        ),
    ]
