# Generated by Django 3.2.9 on 2022-01-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220126_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='star6',
            new_name='start6',
        ),
    ]
