# Generated by Django 4.0.1 on 2022-02-07 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_factory_otk1_factory_otk2_factory_otk3_factory_otk4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='otk1',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 1, 1), verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk2',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 1, 1), verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk3',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 1, 1), verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk4',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 1, 1), verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk5',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 1, 1), verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk6',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 1, 1), verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk7',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 1, 1), verbose_name='ОТК'),
        ),
    ]
