# Generated by Django 4.0.1 on 2022-02-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_factory_otk1_alter_factory_otk2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='otk1',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk2',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk3',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk4',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk5',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk6',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otk7',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
    ]
