# Generated by Django 4.0.1 on 2022-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_factory_otk1_alter_factory_otk2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detal',
            name='end_start1',
        ),
        migrations.RemoveField(
            model_name='detal',
            name='end_start2',
        ),
        migrations.RemoveField(
            model_name='detal',
            name='fill1',
        ),
        migrations.RemoveField(
            model_name='detal',
            name='fill2',
        ),
        migrations.RemoveField(
            model_name='detal',
            name='start_data1',
        ),
        migrations.RemoveField(
            model_name='detal',
            name='start_data2',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='fill3',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='fill4',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='fill5',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='fill6',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='fill7',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='history3',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='history4',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='history5',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='history6',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='history7',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='otk3',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='otk4',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='otk5',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='otk6',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='otk7',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='sent1',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='sent2',
        ),
        migrations.AddField(
            model_name='detal',
            name='history3',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='detal',
            name='history4',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='detal',
            name='history5',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='detal',
            name='history6',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='detal',
            name='history7',
            field=models.TextField(default='', verbose_name='история'),
        ),
        migrations.AddField(
            model_name='detal',
            name='otk3',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
        migrations.AddField(
            model_name='detal',
            name='otk4',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
        migrations.AddField(
            model_name='detal',
            name='otk5',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
        migrations.AddField(
            model_name='detal',
            name='otk6',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
        migrations.AddField(
            model_name='detal',
            name='otk7',
            field=models.TextField(default='', verbose_name='ОТК'),
        ),
    ]
