# Generated by Django 4.0.1 on 2022-02-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_detal_end_start1_remove_detal_end_start2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='end_start3',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='end_start4',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='end_start5',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='end_start6',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='end_start7',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='sent3',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='sent4',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='sent5',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='sent6',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='sent7',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start_data3',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start_data4',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start_data5',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start_data6',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='start_data7',
        ),
    ]
